In [1]:
#ตอนที่ 35 - ลบแถวด้วย Index

import pandas as pd

In [14]:
#เอา indexColumns มาไว้เป็นลำดับแรก
df = pd.read_excel("D:\Destop\Pandas_workshop\pandastutorial-main\Stock.xlsx") 
df

                 Name            Category    Price  Amount
0               เมาส์  อุปกรณ์คอมพิวเตอร์    900.0    10.0
1               ปากกา     อุปกรณ์การเรียน    200.0     5.0
2               โคมไฟ    เครื่องใช้ในบ้าน   1200.0     7.0
3            ไมโครโฟน     เครื่องใช้ไฟฟ้า    750.0     1.0
4       เครื่องซักผ้า     เครื่องใช้ไฟฟ้า   3500.0     0.0
5       เสื้อยืดคอกลม            เสื้อผ้า    500.0     2.0
6         กางเกงยีนต์            เสื้อผ้า    999.0     8.0
7       ตุ๊กตาหมีพูห์             ของเล่น    950.0     5.0
8                โซฟา        เฟอร์นิเจอร์   5000.0     5.0
9                 จาน         เครื่องครัว    250.0     4.0
10               ทีวี     เครื่องใช้ไฟฟ้า  15000.0     7.0
11              ยางลบ     อุปกรณ์การเรียน     20.0     5.0
12  External HardDisk  อุปกรณ์คอมพิวเตอร์   2500.0     7.0
13          คีย์บอร์ด  อุปกรณ์คอมพิวเตอร์    850.0     5.0
14           รถบังคับ             ของเล่น    500.0     6.0

In [16]:
#การลบแถวแบบ ทีละแถว

#ลบแถว 9 ออกไป
rows = 9
df.drop(rows,axis=0,inplace=True)

In [17]:
df

                 Name            Category    Price  Amount
0               เมาส์  อุปกรณ์คอมพิวเตอร์    900.0    10.0
1               ปากกา     อุปกรณ์การเรียน    200.0     5.0
2               โคมไฟ    เครื่องใช้ในบ้าน   1200.0     7.0
3            ไมโครโฟน     เครื่องใช้ไฟฟ้า    750.0     1.0
4       เครื่องซักผ้า     เครื่องใช้ไฟฟ้า   3500.0     0.0
5       เสื้อยืดคอกลม            เสื้อผ้า    500.0     2.0
6         กางเกงยีนต์            เสื้อผ้า    999.0     8.0
7       ตุ๊กตาหมีพูห์             ของเล่น    950.0     5.0
8                โซฟา        เฟอร์นิเจอร์   5000.0     5.0
10               ทีวี     เครื่องใช้ไฟฟ้า  15000.0     7.0
11              ยางลบ     อุปกรณ์การเรียน     20.0     5.0
12  External HardDisk  อุปกรณ์คอมพิวเตอร์   2500.0     7.0
13          คีย์บอร์ด  อุปกรณ์คอมพิวเตอร์    850.0     5.0
14           รถบังคับ             ของเล่น    500.0     6.0

In [18]:
#การลบแถวแบบ หลายๆแถว

#ลบแถว 0,3,10 ออกไป
rows = [0,3,10]
df.drop(rows,axis=0,inplace=True)

In [19]:
df

                 Name            Category   Price  Amount
1               ปากกา     อุปกรณ์การเรียน   200.0     5.0
2               โคมไฟ    เครื่องใช้ในบ้าน  1200.0     7.0
4       เครื่องซักผ้า     เครื่องใช้ไฟฟ้า  3500.0     0.0
5       เสื้อยืดคอกลม            เสื้อผ้า   500.0     2.0
6         กางเกงยีนต์            เสื้อผ้า   999.0     8.0
7       ตุ๊กตาหมีพูห์             ของเล่น   950.0     5.0
8                โซฟา        เฟอร์นิเจอร์  5000.0     5.0
11              ยางลบ     อุปกรณ์การเรียน    20.0     5.0
12  External HardDisk  อุปกรณ์คอมพิวเตอร์  2500.0     7.0
13          คีย์บอร์ด  อุปกรณ์คอมพิวเตอร์   850.0     5.0
14           รถบังคับ             ของเล่น   500.0     6.0